import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { normalizeOfficial } from '../src/data.js';

test('GAS envelope preserves data and top-level returnPlans', () => { const official = normalizeOfficial({ data: { inflationRate: .03, stages: [{ startAge: 60, endAge: 90, ratio: 100 }], returnTables: { PlanA: [{ policy_year: 1, withdrawal_percent: 5, multiplier: 2 }] } }, returnPlans: [{ plan_id: 'a', sheet_name: 'PlanA', display_name: 'Plan A', sort_order: 10, enabled: true }] }); assert.equal(official.data.inflationRate, .03); assert.equal(official.inflationRate, .03); assert.equal(official.returnPlans[0].planId, 'a'); assert.equal(official.returnPlans[0].rows[0].withdrawalRate, 5); });
test('registry dynamically orders enabled plans and maps independent rows', () => { const official = normalizeOfficial({ data: { returnTables: { A: [{ policy_year: 1, withdrawal_percent: 5, multiplier: 2 }], B: [{ policy_year: 1, withdrawal_percent: 10, multiplier: 3 }] } }, returnPlans: [{ plan_id: 'b', sheet_name: 'B', display_name: 'Plan B', sort_order: 20, enabled: true }, { plan_id: 'a', sheet_name: 'A', display_name: 'Plan A', sort_order: 10, enabled: true }, { plan_id: 'off', sheet_name: 'Off', display_name: 'Off', sort_order: 1, enabled: false }] }); assert.deepEqual(official.returnPlans.map((p) => p.planId), ['a', 'b']); assert.equal(official.returnPlans[1].rows[0].withdrawalRate, 10); });
test('plan rows can be carried directly by a registry row', () => { const official = normalizeOfficial({ data: {}, returnPlans: [{ planId: 'c', sheetName: 'C', displayName: 'Plan C', enabled: 'TRUE', rows: [{ policyYear: 6, withdrawalRate: 0, multiplier: 4 }] }] }); assert.equal(official.returnPlans[0].rows[0].policyYear, 6); });
test('official contribution basis is normalized when supplied by GAS', () => { const official = normalizeOfficial({ data: { contribution_years: 5 }, returnPlans: [] }); assert.equal(official.contributionYears, 5); });
test('malformed official payload does not invent a fixed plan', () => { const official = normalizeOfficial({ data: { stages: [] }, returnPlans: [] }); assert.ok(official.stages.length); assert.equal(official.returnPlans.length, 0); });
test('customer data has no GAS POST path', () => { const source = fs.readFileSync(new URL('../src/data.js', import.meta.url), 'utf8'); assert.doesNotMatch(source, /method:\s*['\"]POST['\"]|body:\s*JSON\.stringify/); });
