import { retirementMonthlyNeed, stageSpending, projectResources, retirementGap, purchasingPowerToday } from './calculation.js';
import { loadOfficialData, readUserData, writeUserData } from './data.js';

const money = (n) => Number.isFinite(Number(n)) ? new Intl.NumberFormat('zh-HK', { style: 'currency', currency: 'HKD', maximumFractionDigits: 0 }).format(Number(n)) : '$—';
const state = { step: 0, presentation: false, official: null, source: 'loading', stale: false, data: { retirementAge: 60, planningAge: 90, currentExpense: 30000, inflationRate: 0.025, lifestyle: 'Full retirement', legacy: 'self', resources: 0, resourceGrowth: 3, medicalNote: true } };
const app = document.querySelector('#app');
const saved = readUserData(); state.data = { ...state.data, ...saved };

const questions = [
  { title: '有冇諗過退休之後，想點樣生活？', support: '我哋先由你想要嘅生活開始，唔急住講產品。', type: 'choice', key: 'lifestyle', options: [['Travel & hobbies', '想有時間旅行、做興趣'], ['Some work', '繼續做一部分工作'], ['Full retirement', '完全退休，享受自己時間']] },
  { title: '你希望幾多歲退休？', support: '呢個年齡會影響通脹年數同退休準備時間。', type: 'number', key: 'retirementAge', suffix: '歲', min: 40, max: 85 },
  { title: '你而家每月生活費大約幾多？', support: '先用一個總數了解生活需要，之後可以再調整。', type: 'currency', key: 'currentExpense', suffix: '每月' },
  { title: '退休時，想規劃到幾多歲？', support: '規劃年期會直接影響退休生活總需要。', type: 'number', key: 'planningAge', suffix: '歲', min: 70, max: 110 },
  { title: '退休儲備，主要想照顧邊一個目標？', support: '遺產係獨立目標，唔會偷偷混入生活費計算。', type: 'choice', key: 'legacy', options: [['self', '主要照顧自己'], ['some-legacy', '自己之餘，留一部分'], ['amount', '有明確遺產金額']] },
  { title: '你覺得而家大約已經準備咗幾多退休資源？', support: '先講一個 approximate total，唔需要即刻拆到戶口層級。', type: 'currency', key: 'resources', suffix: '今日資產總額' }
];

function calc() { const d = state.data, years = Math.max(0, d.retirementAge - 45); const monthlyNeed = retirementMonthlyNeed(d.currentExpense, d.inflationRate, years); const stages = stageSpending({ monthlyNeed, retirementAge: d.retirementAge, planningAge: d.planningAge, inflationRate: d.inflationRate, stages: state.official.stages }); const totalNeed = stages.reduce((sum, stage) => sum + stage.total, 0); const projected = projectResources([{ amount: d.resources, growthRate: d.resourceGrowth }], years); return { years, monthlyNeed, stages, totalNeed, projected, gap: retirementGap(totalNeed, projected), purchasingPower: purchasingPowerToday(d.resources, d.inflationRate, years) }; }
function render() { if (!state.official) { app.innerHTML = '<div class="loading">載入 Retire…</div>'; return; } const result = calc(); const q = questions[state.step]; app.innerHTML = `${header()}<section class="content">${state.step === 0 ? intro() : state.step < questions.length ? question(q) : summary(result)}</section>`; bind(result); }
function header() { return `<header class="topbar"><a class="return-ava" href="../avaplatform/" aria-label="返回 AVA">← 返回 AVA</a><div class="brand"><span class="brand-mark">R</span><span>Retire</span></div><div class="top-actions"><span class="status">${state.source === 'cloud' ? '官方資料已更新' : state.stale ? '離線 · 使用本機資料' : '本機資料'}</span><button class="presentation-toggle" type="button">${state.presentation ? '退出展示' : '客戶展示'}</button></div></header>`; }
function intro() { return `<article class="card hero"><p class="eyebrow">退休規劃對話</p><h1>先了解你想要的退休生活。</h1><p>由生活想像開始，慢慢將概念變成數字、視覺同一個可以傾嘅退休目標。</p><button class="primary next" type="button">開始傾</button><p class="fine">所有輸入只保存在此裝置。Retire 不會將客戶資料寫入官方 Google Sheet。</p></article>`; }
function question(q) { return `<div class="step-label">${state.step} / ${questions.length}</div><article class="card"><h1>${q.title}</h1><p class="support">${q.support}</p>${q.type === 'choice' ? `<div class="choices">${q.options.map(([value, label]) => `<button class="choice ${state.data[q.key] === value ? 'selected' : ''}" data-value="${value}" type="button"><span>${label}</span><span class="radio"></span></button>`).join('')}</div>` : `<label class="input-wrap"><span>${q.suffix}</span><input id="answer" type="number" min="${q.min || 0}" max="${q.max || ''}" value="${state.data[q.key] ?? ''}" inputmode="decimal"></label>`}<div class="actions"><button class="secondary back" type="button">${state.step === 1 ? '返回' : '上一題'}</button><button class="primary next" type="button">${state.step === questions.length - 1 ? '睇退休缺口' : '繼續'}</button></div></article>${state.step >= 2 ? `<aside class="mini-result"><span>到退休仲有 ${calc().years} 年</span><strong>每月需要 ${money(calc().monthlyNeed)}</strong></aside>` : ''}`; }
function summary(r) { return `<article class="card summary"><p class="eyebrow">先睇清楚，再傾方法</p><h1>你嘅退休生活，需要幾多？</h1><div class="hero-number"><span>退休時每月生活需要</span><strong>${money(r.monthlyNeed)}</strong><small>以 ${state.data.inflationRate * 100}% 通脹、${r.years} 年估算</small></div><div class="metric-grid"><div><span>退休生活總需要</span><strong>${money(r.totalNeed)}</strong><small>退休至 ${state.data.planningAge} 歲</small></div><div><span>預計退休資源</span><strong>${money(r.projected)}</strong><small>同樣以退休時價值比較</small></div><div class="gap"><span>退休缺口</span><strong>${money(r.gap)}</strong><small>${r.gap > 0 ? '需要再傾點樣處理' : '目前估算資源足以覆蓋'}</small></div></div><div class="stage-visual"><h2>退休支出會分三段</h2>${r.stages.map((s) => `<div class="stage-row"><span>${s.label}</span><div class="bar"><i style="width:${Math.min(100, s.ratio)}%"></i></div><b>${s.ratio}%</b><small>${money(s.total)}</small></div>`).join('')}</div><details><summary>點樣計？</summary><p>今日每月 ${money(state.data.currentExpense)}，按通脹推算到退休年齡；每個退休階段再按你設定的比例調整，通脹仍會繼續計入。${state.data.medicalNote ? '醫療費未混入以上生活需要，將來可接駁獨立 Medical Reserve App。' : ''}</p></details><div class="explore"><h2>下一步可以傾</h2><p>調整退休年齡、生活方式、額外儲蓄，或者探索不同方法。</p><div id="plans">${state.official.returnPlans.map((p) => `<button class="plan" data-plan="${p.planId}" type="button">${p.label}<span>了解方案 →</span></button>`).join('')}</div></div><button class="secondary restart" type="button">重新傾一次</button></article>`; }
function bind(result) { document.querySelector('.next')?.addEventListener('click', () => { const q = questions[state.step]; const input = document.querySelector('#answer'); if (input) state.data[q.key] = Number(input.value); if (state.step < questions.length) state.step += 1; writeUserData(state.data); render(); }); document.querySelector('.back')?.addEventListener('click', () => { state.step = Math.max(1, state.step - 1); render(); }); document.querySelectorAll('.choice').forEach((el) => el.addEventListener('click', () => { state.data[questions[state.step].key] = el.dataset.value; document.querySelectorAll('.choice').forEach((item) => item.classList.remove('selected')); el.classList.add('selected'); })); document.querySelector('.restart')?.addEventListener('click', () => { state.step = 0; render(); }); document.querySelector('.presentation-toggle')?.addEventListener('click', () => { state.presentation = !state.presentation; document.body.classList.toggle('presentation', state.presentation); render(); }); document.querySelectorAll('.plan').forEach((el) => el.addEventListener('click', () => { const plan = state.official.returnPlans.find((p) => p.planId === el.dataset.plan); const first = plan?.rows?.[0]; alert(first ? `${plan.label}\n官方第 ${first.policyYear} 年倍數：${first.multiplier}` : '官方資料暫未提供可用年度。'); })); }
loadOfficialData().then((loaded) => { state.official = loaded.official; state.source = loaded.source; state.stale = loaded.stale; render(); });
