import { purchasingPowerToday, retirementGap, retirementMonthlyNeed, projectResources, retirementTarget, stageSpending, validateAges, yearsUntilRetirement } from './calculation.js';
import { loadOfficialData, readUserData, writeUserData } from './data.js';

const money = (value) => Number.isFinite(Number(value)) ? new Intl.NumberFormat('zh-HK', { style: 'currency', currency: 'HKD', maximumFractionDigits: 0 }).format(Number(value)) : '$—';
const app = document.querySelector('#app');
const saved = readUserData();
const state = { step: 0, presentation: false, official: null, source: 'loading', stale: false, error: '', data: { currentAge: 35, retirementAge: 60, planningAge: 90, currentExpense: 30000, inflationRate: 0.025, lifestyle: 'Full retirement', legacy: 'self', legacyAmount: 0, resources: 0, earmarkedMode: 'amount', earmarkedValue: 0, resourceCategories: {}, resourceGrowth: null, medicalNote: true, ...saved } };

const baseQuestions = [
  { title: '有冇諗過退休之後，想點樣生活？', support: '我哋先由你想要嘅生活開始，唔急住講產品。', type: 'choice', key: 'lifestyle', options: [['Travel & hobbies', '想有時間旅行、做興趣'], ['Some work', '繼續做一部分工作'], ['Full retirement', '完全退休，享受自己時間']] },
  { title: '你而家幾多歲？', support: '用你今日嘅年齡，計算真正到退休仲有幾多年。', type: 'number', key: 'currentAge', suffix: '現時年齡', min: 18, max: 100 },
  { title: '你希望幾多歲退休？', support: '可以同現時年齡一樣；如果早過現時年齡，我哋會停低確認。', type: 'number', key: 'retirementAge', suffix: '退休年齡', min: 40, max: 100 },
  { title: '你而家每月生活費大約幾多？', support: '先用一個總數了解生活需要，之後可以再調整。', type: 'currency', key: 'currentExpense', suffix: '每月' },
  { title: '退休時，想規劃到幾多歲？', support: '規劃年期會直接影響退休生活總需要。', type: 'number', key: 'planningAge', suffix: '規劃到', min: 41, max: 120 },
  { title: '你覺得而家大約已經為退休準備咗幾多？', support: '先講一個 approximate total，唔需要即刻拆到戶口層級。', type: 'currency', key: 'resources', suffix: '今日資產總額' },
  { title: '當中真正預留作退休用途，大約係幾多？', support: '可以用金額或百分比，之後仍然可以調整。', type: 'earmarked', key: 'earmarkedValue', suffix: '預留比例 / 金額' },
  { title: '呢啲退休資源大概來自邊度？', support: '只需要 broad categories；唔需要 account、保單或基金細節。', type: 'categories', key: 'resourceCategories' },
  { title: '先睇購買力，再傾資產會唔會增長', support: '如果今日資產 nominal amount 不變，通脹會令退休時購買力下降。', type: 'purchasing-power', key: 'purchasingPower' },
  { title: '呢筆退休資源本身會唔會增長？', support: '呢個係清楚可調整嘅假設；未知道時可以先用官方 default。', type: 'growth', key: 'resourceGrowth', suffix: '每年名義增長率 %' },
  { title: '退休之後，想唔想留一部分 legacy？', support: 'Legacy 會獨立呈現，唔會偷偷混入生活需要。', type: 'choice', key: 'legacy', options: [['self', '主要照顧自己'], ['some-legacy', '自己之餘，留一部分'], ['amount', '有明確 legacy 金額']] }
];

function questions() { return state.data.legacy === 'amount' ? [...baseQuestions.slice(0, -1), baseQuestions.at(-1), { title: '明確想保留幾多 legacy？', support: '輸入一個實際金額，會獨立加入退休目標並清楚標示。', type: 'currency', key: 'legacyAmount', suffix: 'Legacy 金額' }] : baseQuestions; }
function stages() { return state.data.stages?.length ? state.data.stages : state.official.stages; }
function growthRate() { return state.data.resourceGrowth !== null && state.data.resourceGrowth !== '' && Number.isFinite(Number(state.data.resourceGrowth)) ? Number(state.data.resourceGrowth) : Number(state.official.resourceGrowthRate || 0); }
function earmarkedAmount() { const total = Number(state.data.resources) || 0; return state.data.earmarkedMode === 'percent' ? total * (Number(state.data.earmarkedValue) || 0) / 100 : Number(state.data.earmarkedValue) || 0; }
function calc() {
  const d = state.data; const years = yearsUntilRetirement(d.currentAge, d.retirementAge); if (years === null) return { valid: false, years: null, error: '請先確認現時年齡與退休年齡。' };
  const monthlyNeed = retirementMonthlyNeed(d.currentExpense, d.inflationRate, years);
  const stageRows = stageSpending({ monthlyNeed, retirementAge: d.retirementAge, planningAge: d.planningAge, inflationRate: d.inflationRate, stages: stages() });
  const lifestyleNeed = stageRows.reduce((sum, stage) => sum + stage.total, 0); const legacyNeed = d.legacy === 'amount' ? Number(d.legacyAmount) || 0 : 0; const totalNeed = retirementTarget(lifestyleNeed, legacyNeed);
  const projected = projectResources([{ amount: earmarkedAmount(), growthRate: growthRate() }], years);
  return { valid: true, years, monthlyNeed, stages: stageRows, lifestyleNeed, legacyNeed, totalNeed, projected, gap: retirementGap(totalNeed, projected), purchasingPower: purchasingPowerToday(earmarkedAmount(), d.inflationRate, years), growthRate: growthRate() };
}
function persist() { writeUserData(state.data); }
function header() { return `<header class="topbar"><a class="return-ava" href="../avaplatform/" aria-label="返回 AVA / Return to AVA"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M19 12H5m6-6-6 6 6 6"/></svg><span>返回 AVA</span></a><div class="brand"><span class="brand-mark">R</span><span>Retire</span></div><div class="top-actions"><span class="status">${state.source === 'cloud' ? '官方資料已更新' : state.stale ? '離線 · 使用本機資料' : '本機資料'}</span><button class="presentation-toggle" type="button">${state.presentation ? '退出展示' : '客戶展示'}</button></div></header>`; }
function inputQuestion(q) { const value = state.data[q.key] ?? ''; return `<label class="input-wrap"><span>${q.suffix}</span><input id="answer" type="number" min="${q.min || 0}" max="${q.max || ''}" value="${value}" inputmode="decimal" aria-label="${q.suffix}"></label>`; }
function question(q, result) {
  let body = q.type === 'choice' ? `<div class="choices">${q.options.map(([value, label]) => `<button class="choice ${state.data[q.key] === value ? 'selected' : ''}" data-value="${value}" type="button" aria-pressed="${state.data[q.key] === value}"><span>${label}</span><span class="radio"></span></button>`).join('')}</div>` : inputQuestion(q);
  if (q.type === 'earmarked') body = `<div class="segmented"><button type="button" class="${state.data.earmarkedMode === 'amount' ? 'selected' : ''}" data-mode="amount">金額</button><button type="button" class="${state.data.earmarkedMode === 'percent' ? 'selected' : ''}" data-mode="percent">百分比</button></div>${inputQuestion({ ...q, suffix: state.data.earmarkedMode === 'amount' ? '預留金額' : '預留百分比 %', key: 'earmarkedValue', min: 0, max: state.data.earmarkedMode === 'percent' ? 100 : '' })}<p class="help">約 ${money(earmarkedAmount())} 會用作退休資源比較。</p>`;
  if (q.type === 'categories') body = `<div class="category-grid">${['MPF', 'Investment', 'Saving / Financial Insurance', 'Cash / Fixed Deposit', 'Other'].map((key) => `<label><span>${key}</span><input class="category-input" data-category="${key}" type="number" min="0" max="100" value="${state.data.resourceCategories?.[key] ?? ''}" inputmode="decimal"><small>%</small></label>`).join('')}</div><p class="help">只需 approximate percentage，唔需要任何帳戶或保單資料。</p>`;
  if (q.type === 'purchasing-power') body = `<div class="info-visual"><strong>${money(result?.purchasingPower)}</strong><span>今日約 ${money(earmarkedAmount())}，以 ${result?.years} 年、${state.data.inflationRate * 100}% 通脹計，退休時購買力約為以上數字。</span></div>`;
  return `<div class="step-label">${state.step} / ${questions().length}</div><article class="card"><h1>${q.title}</h1><p class="support">${q.support}</p>${body}<div class="actions"><button class="secondary back" type="button">${state.step === 1 ? '返回' : '上一題'}</button><button class="primary next" type="button">${state.step === questions().length - 1 ? '睇退休缺口' : '繼續'}</button></div><p class="error" role="alert">${state.error}</p></article>${state.step >= 3 && result?.valid ? `<aside class="mini-result"><span>到退休仲有 ${result.years} 年</span><strong>退休時每月需要 ${money(result.monthlyNeed)}</strong></aside>` : ''}`;
}
function planRows(plan) { return `<div class="plan-table"><div class="plan-table-head"><span>保單年度</span><span>領取百分比</span><span>倍數</span></div>${plan.rows.map((row) => `<div><span>${row.policyYear}</span><span>${row.withdrawalRate}%</span><span>${row.multiplier}</span></div>`).join('')}</div>`; }
function summary(result) {
  return `<article class="card summary"><p class="eyebrow">先睇清楚，再傾方法</p><h1>你嘅退休生活，需要幾多？</h1><div class="hero-number"><span>退休時每月生活需要</span><strong>${money(result.monthlyNeed)}</strong><small>現時 ${state.data.currentAge} 歲 → ${state.data.retirementAge} 歲退休，共 ${result.years} 年；以 ${state.data.inflationRate * 100}% 通脹估算</small></div><div class="metric-grid"><div><span>退休生活總需要</span><strong>${money(result.lifestyleNeed)}</strong><small>退休至 ${state.data.planningAge} 歲</small></div><div><span>退休日期預計資源</span><strong>${money(result.projected)}</strong><small>今日 earmarked ${money(earmarkedAmount())}，以 ${result.growthRate}% 增長投影</small></div><div class="gap"><span>退休缺口</span><strong>${money(result.gap)}</strong><small>退休日期需要 − 退休日期資源</small></div></div>${result.legacyNeed ? `<div class="separate-need"><span>獨立 Legacy 目標</span><strong>${money(result.legacyNeed)}</strong><small>已清楚列出，沒有混入生活費。</small></div>` : ''}<div class="stage-visual"><h2>退休階段（可調整）</h2><p class="help">你可以直接調整年齡段和百分比；通脹會持續跨越所有階段。</p>${result.stages.map((s, index) => `<div class="stage-row"><label><span>${s.label || `階段 ${index + 1}`}</span><input class="stage-input" data-stage="${index}" data-field="startAge" type="number" value="${s.startAge}">–<input class="stage-input" data-stage="${index}" data-field="endAge" type="number" value="${s.endAge}"> 歲</label><input class="stage-input ratio-input" data-stage="${index}" data-field="ratio" type="number" min="0" value="${s.ratio}"><b>%</b><small>${money(s.total)}</small></div>`).join('')}</div><details><summary>購買力與增長假設</summary><p>如果今日 earmarked 資產 nominal amount 不變，退休時購買力約為 ${money(result.purchasingPower)}。目前使用 ${result.growthRate}% 名義資產增長；這不是隱藏假設，可以在對話中調整。</p></details><div class="explore"><h2>探索一個可能方法</h2><p>以下只讀官方 Dynamic Return Plan 的每年資料，不會自行推算 withdrawal pattern。</p>${state.official.returnPlans.length ? state.official.returnPlans.map((p) => `<details class="plan"><summary>${p.label || p.planId}<span>${p.rows.length} 年官方資料</span></summary>${planRows(p)}</details>`).join('') : '<p class="help">目前 Official Cache 沒有可用方案；不會用固定方案補值。</p>'}</div><button class="secondary restart" type="button">重新傾一次</button></article>`;
}
function render() { if (!state.official) { app.innerHTML = '<div class="loading">載入 Retire…</div>'; return; } const result = calc(); const active = questions(); const q = active[state.step]; app.innerHTML = `${header()}<section class="content">${state.step === 0 ? '<article class="card hero"><p class="eyebrow">退休規劃對話</p><h1>先了解你想要嘅退休生活。</h1><p>由生活想像開始，慢慢將概念變成數字、視覺同一個可以傾嘅退休目標。</p><button class="primary next" type="button">開始傾</button><p class="fine">所有輸入只保存在此裝置。Retire 不會將客戶資料寫入官方 Google Sheet。</p></article>' : state.step < active.length ? question(q, result) : result.valid ? summary(result) : '<article class="card"><h1>請先確認資料</h1><p class="error">年齡資料未能計算，請返回修正。</p><button class="primary back" type="button">返回</button></article>'}</section>`; bind(result); }
function bind(result) {
  document.querySelector('.next')?.addEventListener('click', () => { const q = questions()[state.step]; const input = document.querySelector('#answer'); if (input && q?.type !== 'purchasing-power') state.data[q.key] = Number(input.value); if (q?.type === 'categories') document.querySelectorAll('.category-input').forEach((el) => { state.data.resourceCategories[el.dataset.category] = Number(el.value) || 0; }); if (q?.type === 'number' || q?.key === 'currentAge' || q?.key === 'retirementAge' || q?.key === 'planningAge') { const check = validateAges(state.data.currentAge, state.data.retirementAge, state.data.planningAge); if (!check.valid && state.step >= 4) { state.error = check.reason; render(); return; } } state.error = ''; persist(); if (state.step < questions().length) state.step += 1; render(); });
  document.querySelector('.back')?.addEventListener('click', () => { state.step = Math.max(1, state.step - 1); state.error = ''; render(); });
  document.querySelectorAll('.choice').forEach((el) => el.addEventListener('click', () => { state.data[questions()[state.step].key] = el.dataset.value; persist(); render(); }));
  document.querySelectorAll('[data-mode]').forEach((el) => el.addEventListener('click', () => { state.data.earmarkedMode = el.dataset.mode; render(); }));
  document.querySelectorAll('.stage-input').forEach((el) => el.addEventListener('change', () => { const index = Number(el.dataset.stage); const updated = state.data.stages?.length ? [...state.data.stages] : stages().map((stage) => ({ ...stage })); updated[index][el.dataset.field] = Number(el.value); state.data.stages = updated; persist(); render(); }));
  document.querySelector('.restart')?.addEventListener('click', () => { state.step = 0; render(); });
  document.querySelector('.presentation-toggle')?.addEventListener('click', () => { state.presentation = !state.presentation; document.body.classList.toggle('presentation', state.presentation); render(); });
}

loadOfficialData().then((loaded) => { state.official = loaded.official; state.source = loaded.source; state.stale = loaded.stale; if (state.data.resourceGrowth === null || state.data.resourceGrowth === '') state.data.resourceGrowth = loaded.official.resourceGrowthRate; if (!state.data.resourceCategories) state.data.resourceCategories = {}; render(); });
if ('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js').catch(() => {});
